services:
    db:
        image: postgres
        restart: always
        hostname: db
        environment:
            POSTGRES_PASSWORD: 123456789
        ports:
            - "5432:5432"
        expose:
            - "5432"
        volumes:
            - postgres:/var/lib/postgresql/data
        networks:
            - outside
            - default

    pgadmin:
        image: dpage/pgadmin4
        restart: always
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@admin.com
            - PGADMIN_DEFAULT_PASSWORD=pgadmin4
        ports:
            - "5050:80"
        depends_on:
            - db
        networks:
            - outside
            - default

    backend:
        build: ./backend
        restart: always
        hostname: back
        ports:
            - "5000:5000"
        environment:
            - BACK_PORT=5000
            - DB_HOST=db
            - ARCHIVE_KEY=test
            - ARCHIVE_USER=test
        networks:
            - outside
            - default
        volumes:
            -   "archivematica_storage_service_location_data:/var/archivematica"

    frontend:
        build: ./frontend
        restart: always
        environment:
            - BACK_HOST=back
        ports:
            - "3000:3000"
        networks:
            - outside
            - default

volumes:
    postgres:

    archivematica_storage_service_location_data:
        name: "ss-location-data"
        external: true

networks:
    outside:
        name: am_default
        external: true