services:
    db:
        container_name: postgres
        image: postgres
        restart: always
        hostname: db
        environment:
            POSTGRES_PASSWORD: 123456789
        ports:
            - "5432:5432"
        expose:
            - "5432"
        volumes:
            - postgres:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        restart: always
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@admin.com
            - PGADMIN_DEFAULT_PASSWORD=pgadmin4
        ports:
            - "5050:80"
        depends_on:
            - db

    backend:
        build: ./backend
        restart: always
        ports:
            - "5000:5000"
        environment:
            - BACK_PORT=5000
            - DB_HOST=db

volumes:
    postgres:
